"use client";
import {useEffect,useState} from "react";
import {api} from "../../../../lib/api";

type Analysis={candidate_id:string;summary:string;strengths:string[];gaps:string[];considerations:string[]};
type MatchResult={count:number;ai_available:boolean;analyses:Analysis[];pricing?:{currency:string;unit_price:number;unit:string};quote?:{quantity:number;total:number};coverage?:{requested:number;returned:number;missing_candidate_ids:string[]}};
const UNIT_PRICE=2.99;
export default function Vacante({params}:any){
  const code=params.code;
  const [items,setItems]=useState<any[]>([]),[delivery,setDelivery]=useState<any>(null),[msg,setMsg]=useState("");
  const [matches,setMatches]=useState<MatchResult|null>(null),[selected,setSelected]=useState<string[]>([]),[matching,setMatching]=useState(false),[accepting,setAccepting]=useState(false);
  useEffect(()=>{api("/v1/company/vacancies").then(x=>setItems(x.items)).catch(()=>setMsg("No se pudo cargar la solicitud."));api("/v1/company/vacancies/"+code+"/delivery").then(setDelivery).catch(()=>{})},[code]);
  const v=items.find(x=>x.vacancy_code===code),eventual=v?.request_type==="EVENTUAL";
  const unitPrice=matches?.pricing?.unit_price??UNIT_PRICE,selectedTotal=Number((selected.length*unitPrice).toFixed(2));
  async function payment(e:any){e.preventDefault();const f=new FormData(e.currentTarget);setMsg("Enviando referencia…");try{await api("/v1/company/vacancies/"+code+"/payment",{method:"POST",body:JSON.stringify({reference:f.get("reference"),notes:f.get("notes")})});setMsg("Pago enviado para revisión.");const refreshed=await api("/v1/company/vacancies");setItems(refreshed.items);}catch{setMsg("No se pudo enviar el pago.")}}
  async function findMatches(){setMatching(true);setMsg("Buscando perfiles compatibles…");try{const result=await api("/v1/company/vacancies/"+code+"/matches");setMatches(result);setSelected([]);setMsg(result.count?`Encontramos ${result.count} perfil(es) compatible(s). Cada candidatura entregada cuesta $${Number(result.pricing?.unit_price??UNIT_PRICE).toFixed(2)}.`:"Por ahora no encontramos perfiles compatibles activos.");}catch{setMsg("No se pudo completar la búsqueda de perfiles en este momento.");}finally{setMatching(false)}}
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
  async function acceptCandidates(){if(!selected.length)return;setAccepting(true);setMsg(`Confirmando ${selected.length} candidatura(s) por $${selectedTotal.toFixed(2)}…`);try{const result=await api("/v1/company/vacancies/"+code+"/candidates/accept",{method:"POST",body:JSON.stringify({candidate_ids:selected,confirm_price:true})});setSelected([]);setMatches(null);const refreshed=await api("/v1/company/vacancies");setItems(refreshed.items);if(result.status==="ENTREGADA"){const delivered=await api("/v1/company/vacancies/"+code+"/delivery");setDelivery(delivered);setMsg(`${result.accepted} candidatura(s) entregada(s). Total confirmado: $${Number(result.quote?.total??selectedTotal).toFixed(2)}.`);}else if(result.payment_required){setMsg(`${result.accepted} candidatura(s) reservada(s). Total: $${Number(result.quote?.total??selectedTotal).toFixed(2)}. Continúa con el pago para recibir los datos de contacto.`);}else setMsg(`${result.accepted} candidatura(s) aceptada(s). Total confirmado: $${Number(result.quote?.total??selectedTotal).toFixed(2)}.`);}catch{setMsg("No se pudieron aceptar esas candidaturas. La disponibilidad pudo haber cambiado.");}finally{setAccepting(false)}}
  return <main className="portal"><header><a href="/empresa">Empleos.pa</a><span>{code}</span></header><section>
    <p className="eyebrowDark">{eventual?"SERVICIO O TRABAJO EVENTUAL":"VACANTE"}</p><h1>{v?.position||code}</h1>
    {v&&<div className="vacancyStatus"><span>Estado actual</span><strong>{v.status}</strong><p>{eventual?"Solicitud de servicio":`${v.quantity} puesto(s)`} · {v.work_location}</p></div>}
    <p className="saveMsg" role="status" aria-live="polite">{msg}</p>
    {v?.status==="PENDIENTE_PAGO"&&<form className="paymentForm" onSubmit={payment}><h2>Reportar pago</h2><p>Ingresa la referencia del pago de <strong>${Number(v.package_price||0).toFixed(2)}</strong>. Empleos.pa la revisará antes de entregar las candidaturas seleccionadas.</p><label className="wfield">Referencia<input name="reference" required/></label><label className="wfield">Observación<textarea name="notes" rows={3}/></label><button className="portalAction" type="submit">Enviar a revisión</button></form>}
    {v?.status==="PAGO_EN_REVISION"&&<div className="infoBox"><strong>Pago en revisión</strong><p>Te mostraremos el nuevo estado cuando sea aprobado o rechazado.</p></div>}
    {["APROBADA","EN_BUSQUEDA"].includes(v?.status)&&<div className="infoBox"><strong>{v.status==="APROBADA"?"Solicitud lista para búsqueda":"Búsqueda en proceso"}</strong><p>{eventual?"Estamos buscando prestadores activos compatibles con el servicio, la ubicación y la disponibilidad que indicaste.":"Busca perfiles activos compatibles. Solo pagas por las candidaturas que decidas recibir."}</p>{!eventual&&<button className="portalAction" type="button" onClick={findMatches} disabled={matching}>{matching?"Buscando…":"Buscar perfiles compatibles"}</button>}</div>}
    {!eventual&&matches&&<div className="infoBox"><p className="eyebrowDark">PERFILES COMPATIBLES</p><h2>{matches.count} perfil(es) encontrado(s)</h2><p><strong>${unitPrice.toFixed(2)} por candidatura entregada.</strong> Selecciona únicamente las que quieras recibir.</p>{!matches.ai_available&&matches.count>0&&<p>La búsqueda estructurada encontró perfiles, pero el análisis descriptivo no está disponible todavía.</p>}{matches.analyses?.length>0&&<div className="adminList">{matches.analyses.map((x,i)=><article key={x.candidate_id}><label style={{display:"block"}}><input type="checkbox" checked={selected.includes(x.candidate_id)} onChange={()=>toggle(x.candidate_id)}/> <strong>Perfil compatible {i+1}</strong></label><p>{x.summary}</p>{x.strengths?.length>0&&<p><strong>Fortalezas relacionadas:</strong> {x.strengths.join(" · ")}</p>}{x.gaps?.length>0&&<p><strong>Aspectos por verificar:</strong> {x.gaps.join(" · ")}</p>}{x.considerations?.length>0&&<p><strong>Consideraciones:</strong> {x.considerations.join(" · ")}</p>}</article>)}</div>}{matches.analyses?.length>0&&<><p>El análisis es descriptivo. Empleos.pa no clasifica candidatos ni decide contrataciones.</p><div className="vacancyStatus"><span>Resumen</span><strong>{selected.length} candidatura(s) × ${unitPrice.toFixed(2)} = ${selectedTotal.toFixed(2)}</strong></div><button className="portalAction" type="button" onClick={acceptCandidates} disabled={!selected.length||accepting}>{accepting?"Confirmando…":selected.length?`Aceptar y continuar · $${selectedTotal.toFixed(2)}`:"Selecciona candidaturas"}</button></>}</div>}
    {["ENTREGADA","CERRADA"].includes(v?.status)&&<div className="infoBox"><strong>{eventual?"Prestadores compatibles entregados":"Candidaturas entregadas"}</strong><p>{eventual?"Puedes contactar directamente a los prestadores entregados.":"Puedes contactar directamente a las personas entregadas para entrevistar, verificar información y continuar tu proceso."}</p></div>}
    {delivery?.report&&<div className="infoBox"><p className="eyebrowDark">REPORTE DESCRIPTIVO</p><h2>{eventual?"Prestadores compatibles":delivery.report.title}</h2><p><strong>Solicitud:</strong> {delivery.report.vacancy_code} · <strong>Ubicación:</strong> {delivery.report.work_location}</p><p><strong>Perfiles entregados:</strong> {delivery.report.total_profiles} · <strong>Fecha:</strong> {new Date(delivery.report.generated_at).toLocaleDateString("es-PA")}</p><p>{eventual?"Empleos.pa facilita el contacto; las condiciones del servicio se acuerdan directamente.":delivery.report.notice}</p></div>}
    {delivery?.candidates?.length>0&&<div className="adminList">{delivery.candidates.map((x:any)=><article key={x.candidate_code}><div><strong>{x.candidate_code} · {x.full_name}</strong><p>{x.primary_job_area} · {x.province}, {x.district}</p><p>{x.work_profile}</p><p><strong>Contacto:</strong> {x.phone}{x.email?" · "+x.email:""}</p>{!eventual&&<p><strong>Habilidades:</strong> {x.skills||"No indicadas"}</p>}</div></article>)}</div>}
  </section></main>
}
