"use client";
import {useEffect,useState} from "react";
import {api} from "../../../../lib/api";

type Analysis={candidate_id:string;summary:string;strengths:string[];gaps:string[];considerations:string[]};
type MatchResult={count:number;ai_available:boolean;analyses:Analysis[];coverage?:{requested:number;returned:number;missing_candidate_ids:string[]}};

export default function Vacante({params}:any){
  const code=params.code;
  const [items,setItems]=useState<any[]>([]),[delivery,setDelivery]=useState<any>(null),[msg,setMsg]=useState("");
  const [matches,setMatches]=useState<MatchResult|null>(null),[selected,setSelected]=useState<string[]>([]),[matching,setMatching]=useState(false),[accepting,setAccepting]=useState(false);
  useEffect(()=>{api("/v1/company/vacancies").then(x=>setItems(x.items)).catch(()=>setMsg("No se pudo cargar la solicitud."));api("/v1/company/vacancies/"+code+"/delivery").then(setDelivery).catch(()=>{})},[code]);
  const v=items.find(x=>x.vacancy_code===code),eventual=v?.request_type==="EVENTUAL";
  async function payment(e:any){e.preventDefault();const f=new FormData(e.currentTarget);setMsg("Enviando referencia…");try{await api("/v1/company/vacancies/"+code+"/payment",{method:"POST",body:JSON.stringify({reference:f.get("reference"),notes:f.get("notes")})});setMsg("Pago enviado para revisión.")}catch{setMsg("No se pudo enviar el pago.")}}
  async function findMatches(){setMatching(true);setMsg("Buscando perfiles compatibles…");try{const result=await api("/v1/company/vacancies/"+code+"/matches");setMatches(result);setSelected([]);setMsg(result.count?`Encontramos ${result.count} perfil(es) compatible(s) para revisar.`:"Por ahora no encontramos perfiles compatibles activos.");}catch{setMsg("No se pudo completar la búsqueda de perfiles en este momento.");}finally{setMatching(false)}}
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
  async function acceptCandidates(){if(!selected.length)return;setAccepting(true);setMsg("Guardando perfiles aceptados…");try{const result=await api("/v1/company/vacancies/"+code+"/candidates/accept",{method:"POST",body:JSON.stringify({candidate_ids:selected})});setMsg(`${result.accepted} perfil(es) aceptado(s). La solicitud continúa en búsqueda hasta preparar la entrega.`);setSelected([]);const refreshed=await api("/v1/company/vacancies");setItems(refreshed.items);}catch{setMsg("No se pudieron aceptar esos perfiles. La disponibilidad pudo haber cambiado.");}finally{setAccepting(false)}}
  return <main className="portal"><header><a href="/empresa">Empleos.pa</a><span>{code}</span></header><section>
    <p className="eyebrowDark">{eventual?"SERVICIO O TRABAJO EVENTUAL":"VACANTE"}</p><h1>{v?.position||code}</h1>
    {v&&<div className="vacancyStatus"><span>Estado actual</span><strong>{v.status}</strong><p>{eventual?"Solicitud de servicio":`${v.quantity} puesto(s)`} · {v.work_location}</p>{v.package_price&&<p><strong>{eventual?"Tarifa:":"Paquete:"}</strong> {eventual?"Servicio o trabajo eventual":v.package==="DISPONIBLES"?"Perfiles compatibles disponibles":(v.package_candidate_limit+" candidatos")} · <strong>{"$"+Number(v.package_price).toFixed(2)}</strong></p>}</div>}
    <p className="saveMsg" role="status" aria-live="polite">{msg}</p>
    {v?.status==="PENDIENTE_PAGO"&&<form className="paymentForm" onSubmit={payment}><h2>Reportar pago</h2><p>Ingresa la referencia del pago de <strong>{"$"+Number(v.package_price||0).toFixed(2)}</strong>. Empleos.pa la revisará antes de iniciar la búsqueda.</p><label className="wfield">Referencia<input name="reference" required/></label><label className="wfield">Observación<textarea name="notes" rows={3}/></label><button className="portalAction" type="submit">Enviar a revisión</button></form>}
    {v?.status==="PAGO_EN_REVISION"&&<div className="infoBox"><strong>Pago en revisión</strong><p>Te mostraremos el nuevo estado cuando sea aprobado o rechazado.</p></div>}
    {["APROBADA","EN_BUSQUEDA"].includes(v?.status)&&<div className="infoBox"><strong>{v.status==="APROBADA"?"Solicitud lista para búsqueda":"Búsqueda en proceso"}</strong><p>{v.status==="APROBADA"?"Tu solicitud está aprobada. Durante la promoción de lanzamiento no necesitas reportar un pago.":eventual?"Estamos buscando prestadores activos compatibles con el servicio, la ubicación y la disponibilidad que indicaste.":"Estamos trabajando con perfiles activos y compatibles con tu solicitud."}</p>{!eventual&&<button className="portalAction" type="button" onClick={findMatches} disabled={matching}>{matching?"Buscando…":"Buscar perfiles compatibles"}</button>}</div>}
    {!eventual&&matches&&<div className="infoBox"><p className="eyebrowDark">PERFILES COMPATIBLES</p><h2>{matches.count} perfil(es) encontrado(s)</h2>{!matches.ai_available&&matches.count>0&&<p>La búsqueda estructurada encontró perfiles, pero el análisis descriptivo no está disponible todavía.</p>}{matches.analyses?.length>0&&<div className="adminList">{matches.analyses.map((x,i)=><article key={x.candidate_id}><label style={{display:"block"}}><input type="checkbox" checked={selected.includes(x.candidate_id)} onChange={()=>toggle(x.candidate_id)}/> <strong>Perfil compatible {i+1}</strong></label><p>{x.summary}</p>{x.strengths?.length>0&&<p><strong>Fortalezas relacionadas:</strong> {x.strengths.join(" · ")}</p>}{x.gaps?.length>0&&<p><strong>Aspectos por verificar:</strong> {x.gaps.join(" · ")}</p>}{x.considerations?.length>0&&<p><strong>Consideraciones:</strong> {x.considerations.join(" · ")}</p>}</article>)}</div>}{matches.analyses?.length>0&&<><p>El análisis es descriptivo y se basa en información declarada. Empleos.pa no clasifica candidatos ni decide contrataciones.</p><button className="portalAction" type="button" onClick={acceptCandidates} disabled={!selected.length||accepting}>{accepting?"Guardando…":`Aceptar ${selected.length||0} perfil(es)`}</button></>}</div>}
    {["ENTREGADA","CERRADA"].includes(v?.status)&&<div className="infoBox"><strong>{v?.status==="CERRADA"?(eventual?"Servicio cerrado":"Perfiles entregados"):(eventual?"Prestadores compatibles entregados":"Preselección entregada")}</strong><p>{eventual?"Estos prestadores fueron incluidos por compatibilidad con tu solicitud. Puedes contactarlos directamente, explicar el trabajo y acordar con ellos disponibilidad, condiciones y precio.":"Estos perfiles fueron incluidos en la preselección de tu solicitud. Puedes contactarlos directamente para entrevistar, verificar información y continuar tu proceso."}</p></div>}
    {delivery?.report&&<div className="infoBox"><p className="eyebrowDark">REPORTE DESCRIPTIVO</p><h2>{eventual?"Prestadores compatibles":delivery.report.title}</h2><p><strong>Solicitud:</strong> {delivery.report.vacancy_code} · <strong>Tipo:</strong> {eventual?"Servicio o trabajo eventual":"Vacante"}</p><p><strong>{eventual?"Servicio":"Puesto"}:</strong> {delivery.report.position} · <strong>Ubicación:</strong> {delivery.report.work_location}</p><p><strong>{eventual?"Prestadores entregados":"Perfiles entregados"}:</strong> {delivery.report.total_profiles} · <strong>Fecha:</strong> {new Date(delivery.report.generated_at).toLocaleDateString("es-PA")}</p><p>{eventual?"La compatibilidad se basa en la información declarada por cada prestador. Empleos.pa facilita el contacto; el solicitante y el prestador acuerdan directamente las condiciones y el precio del servicio.":delivery.report.notice}</p></div>}
    {delivery?.candidates?.length>0&&<div className="adminList">{delivery.candidates.map((x:any)=><article key={x.candidate_code}><div><strong>{x.candidate_code} · {x.full_name}</strong><p>{x.primary_job_area} · {x.province}, {x.district}</p><p>{x.work_profile}</p><p><strong>Contacto:</strong> {x.phone}{x.email?" · "+x.email:""}</p>{!eventual&&<p><strong>Habilidades:</strong> {x.skills||"No indicadas"}</p>}</div></article>)}</div>}
    {v?.status==="CERRADA"&&<div className="infoBox"><strong>Proceso cerrado</strong><p>{eventual?"Esta solicitud de servicio ya completó su ciclo en Empleos.pa. Los prestadores entregados permanecen disponibles en este historial.":"Esta solicitud ya completó su ciclo en Empleos.pa. Los perfiles entregados permanecen disponibles en este historial."}</p></div>}
  </section></main>
}
