import type {FastifyInstance} from "fastify";
import {db} from "./db.js";
import {requireRoles} from "./rbac.js";
import {writeAdminAudit} from "./admin-audit.js";

type XlsxCell=string|number|boolean|null|undefined;
type XlsxSheet={name:string;headers:string[];rows:XlsxCell[][]};

const xmlEscape=(value:XlsxCell)=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
const colName=(index:number)=>{let n=index+1,out="";while(n){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26);}return out;};
const crcTable=(()=>{const table:number[]=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;})();
const crc32=(data:Buffer)=>{let c=0xffffffff;for(const byte of data)c=crcTable[(c^byte)&0xff]^(c>>>8);return (c^0xffffffff)>>>0;};
function zipStore(files:{name:string;data:Buffer}[]){const local:Buffer[]=[];const central:Buffer[]=[];let offset=0;for(const file of files){const name=Buffer.from(file.name);const crc=crc32(file.data);const lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(0x0800,6);lh.writeUInt16LE(0,8);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(file.data.length,18);lh.writeUInt32LE(file.data.length,22);lh.writeUInt16LE(name.length,26);local.push(lh,name,file.data);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt16LE(0x0800,8);ch.writeUInt16LE(0,10);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(file.data.length,20);ch.writeUInt32LE(file.data.length,24);ch.writeUInt16LE(name.length,28);ch.writeUInt32LE(offset,42);central.push(ch,name);offset+=lh.length+name.length+file.data.length;}const centralSize=central.reduce((n,b)=>n+b.length,0);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,...central,end]);}
function worksheetXml(sheet:XlsxSheet){const all=[sheet.headers,...sheet.rows];const rows=all.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>{const ref=colName(c)+(r+1);if(typeof value==="number"&&Number.isFinite(value))return `<c r="${ref}"><v>${value}</v></c>`;if(typeof value==="boolean")return `<c r="${ref}" t="b"><v>${value?1:0}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(value)}</t></is></c>`;}).join("")}</row>`).join("");return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows}</sheetData></worksheet>`;}
function buildXlsx(sheets:XlsxSheet[]){const files:{name:string;data:Buffer}[]=[];const add=(name:string,data:string)=>files.push({name,data:Buffer.from(data,"utf8")});add("[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`);add("_rels/.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`);add("xl/workbook.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xmlEscape(s.name.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`);add("xl/_rels/workbook.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}</Relationships>`);sheets.forEach((s,i)=>add(`xl/worksheets/sheet${i+1}.xml`,worksheetXml(s)));return zipStore(files);}

export async function adminRoutes(app:FastifyInstance){
app.get("/v1/admin/summary",{preHandler:requireRoles("ADMIN")},async()=>{const [users,candidates,companies,vacancies,payments,revenue,revenueToday,revenueWeek,revenueMonth,newToday,newWeek,newMonth,expiring,deliveries,notices,unreadNotices]=await Promise.all([
db.query("select role,count(*)::int total from users group by role"),db.query("select status,count(*)::int total from candidate_profiles group by status"),db.query("select count(*)::int total from companies"),db.query("select status,count(*)::int total from vacancies group by status"),db.query("select status,count(*)::int total from vacancy_payments group by status"),db.query("select coalesce(sum(amount),0)::text total from vacancy_payments where status='APROBADO'"),db.query("select coalesce(sum(amount),0)::text total from vacancy_payments where status='APROBADO' and created_at>=current_date"),db.query("select coalesce(sum(amount),0)::text total from vacancy_payments where status='APROBADO' and created_at>=now()-interval '7 days'"),db.query("select coalesce(sum(amount),0)::text total from vacancy_payments where status='APROBADO' and created_at>=now()-interval '30 days'"),db.query("select count(*)::int total from candidate_profiles where created_at>=current_date"),db.query("select count(*)::int total from candidate_profiles where created_at>=now()-interval '7 days'"),db.query("select count(*)::int total from candidate_profiles where created_at>=now()-interval '30 days'"),db.query("select count(*)::int total from candidate_profiles where status='ACTIVO' and valid_until between current_date and current_date+interval '7 days'"),db.query("select count(*)::int total from vacancy_deliveries where status='ENVIADA'"),db.query("select count(*)::int total from candidate_notifications"),db.query("select count(*)::int total from candidate_notifications where read_at is null")]);return {users:Object.fromEntries(users.rows.map(x=>[x.role,x.total])),candidates:Object.fromEntries(candidates.rows.map(x=>[x.status,x.total])),companies:companies.rows[0]?.total??0,vacancies:Object.fromEntries(vacancies.rows.map(x=>[x.status,x.total])),payments:Object.fromEntries(payments.rows.map(x=>[x.status,x.total])),revenue:revenue.rows[0]?.total??"0",revenue_periods:{today:revenueToday.rows[0]?.total??"0",last_7_days:revenueWeek.rows[0]?.total??"0",last_30_days:revenueMonth.rows[0]?.total??"0"},new_candidates:{today:newToday.rows[0]?.total??0,last_7_days:newWeek.rows[0]?.total??0,last_30_days:newMonth.rows[0]?.total??0},candidates_expiring_7_days:expiring.rows[0]?.total??0,deliveries_sent:deliveries.rows[0]?.total??0,candidate_notices:notices.rows[0]?.total??0,unread_candidate_notices:unreadNotices.rows[0]?.total??0};});
app.get("/v1/admin/candidates",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const status=typeof req.query?.status==="string"?req.query.status:null;const validStatuses=["BORRADOR","ACTIVO","VENCIDO","RETIRADO"];if(status&&!validStatuses.includes(status))return reply.code(400).send({error:"INVALID_STATUS"});const search=typeof req.query?.q==="string"?req.query.q.trim():"";if(search.length>200)return reply.code(400).send({error:"INVALID_SEARCH"});const values:any[]=[];const where:string[]=[];if(status){values.push(status);where.push("cp.status=$"+values.length);}if(search){values.push("%"+search+"%");where.push("(cp.candidate_code ilike $"+values.length+" or cp.full_name ilike $"+values.length+" or cp.primary_job_area ilike $"+values.length+" or cp.province ilike $"+values.length+")");}const q=await db.query("select cp.candidate_id,cp.candidate_code,cp.status,cp.full_name,cp.province,cp.district,cp.primary_job_area,cp.valid_until,cp.created_at from candidate_profiles cp "+(where.length?"where "+where.join(" and "):"")+" order by cp.created_at desc limit 100",values);return {items:q.rows};});
app.get("/v1/admin/companies",{preHandler:requireRoles("ADMIN")},async()=>{const q=await db.query("select company_id,name,contact_name,province,district,created_at from companies order by created_at desc limit 100");return {items:q.rows};});
app.get("/v1/admin/vacancies",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const status=typeof req.query?.status==="string"?req.query.status:null;const validStatuses=["RECIBIDA","PENDIENTE_PAGO","PAGO_EN_REVISION","APROBADA","EN_BUSQUEDA","ENTREGADA","CERRADA","CANCELADA"];if(status&&!validStatuses.includes(status))return reply.code(400).send({error:"INVALID_STATUS"});const values:any[]=[];let where="";if(status){values.push(status);where="where v.status=$1";}const q=await db.query("select v.vacancy_id,v.vacancy_code,v.status,v.request_type,v.position,v.quantity,v.work_location,v.package,v.package_candidate_limit,v.package_price,v.created_at,c.name company_name from vacancies v join companies c on c.company_id=v.company_id "+where+" order by v.created_at desc limit 100",values);return {items:q.rows};});
app.get("/v1/admin/notifications",{preHandler:requireRoles("ADMIN")},async()=>{const q=await db.query("select 'PAYMENT_REVIEW' type,p.payment_id::text id,v.vacancy_code code,c.name source,p.created_at created_at,'Pago pendiente de revisión' title from vacancy_payments p join vacancies v on v.vacancy_id=p.vacancy_id join companies c on c.company_id=v.company_id where p.status='EN_REVISION' and v.status='PAGO_EN_REVISION' union all select 'VACANCY_READY' type,v.vacancy_id::text id,v.vacancy_code code,c.name source,v.updated_at created_at,'Solicitud lista para búsqueda' title from vacancies v join companies c on c.company_id=v.company_id where v.status='APROBADA' order by created_at desc limit 100");return {items:q.rows};});
app.get("/v1/admin/export.xlsx",{preHandler:requireRoles("ADMIN")},async(_req,reply)=>{const [candidates,companies,vacancies,payments,deliveries]=await Promise.all([
db.query("select cp.candidate_code,cp.status,cp.full_name,cp.phone,u.email,cp.province,cp.district,cp.primary_job_area,cp.available_from,cp.valid_until,cp.created_at from candidate_profiles cp join users u on u.user_id=cp.user_id order by cp.created_at desc"),
db.query("select c.name,c.contact_name,c.phone,c.email,c.province,c.district,c.created_at from companies c order by c.created_at desc"),
db.query("select v.vacancy_code,v.status,v.request_type,v.position,v.quantity,v.work_location,v.package,v.package_candidate_limit,v.package_price,c.name company_name,v.created_at from vacancies v join companies c on c.company_id=v.company_id order by v.created_at desc"),
db.query("select v.vacancy_code,c.name company_name,p.status,p.amount,p.reference,p.submitted_at,p.reviewed_at,p.created_at from vacancy_payments p join vacancies v on v.vacancy_id=p.vacancy_id join companies c on c.company_id=v.company_id order by p.created_at desc"),
db.query("select v.vacancy_code,c.name company_name,d.status,d.sent_at,d.created_at,count(dc.delivery_candidate_id)::int profiles from vacancy_deliveries d join vacancies v on v.vacancy_id=d.vacancy_id join companies c on c.company_id=v.company_id left join vacancy_delivery_candidates dc on dc.delivery_id=d.delivery_id group by d.delivery_id,v.vacancy_code,c.name order by d.created_at desc")
]);const val=(x:any)=>x instanceof Date?x.toISOString():x;const rows=(items:any[],keys:string[])=>items.map(item=>keys.map(k=>val(item[k])));const sheets:XlsxSheet[]=[
{name:"Candidatos",headers:["Código","Estado","Nombre","Teléfono","Correo","Provincia","Distrito","Área principal","Disponible desde","Vigente hasta","Creado"],rows:rows(candidates.rows,["candidate_code","status","full_name","phone","email","province","district","primary_job_area","available_from","valid_until","created_at"])},
{name:"Empresas",headers:["Empresa","Contacto","Teléfono","Correo","Provincia","Distrito","Creada"],rows:rows(companies.rows,["name","contact_name","phone","email","province","district","created_at"])},
{name:"Vacantes",headers:["Código","Estado","Tipo","Puesto/oficio","Cantidad","Ubicación","Paquete","Límite perfiles","Precio","Empresa","Creada"],rows:rows(vacancies.rows,["vacancy_code","status","request_type","position","quantity","work_location","package","package_candidate_limit","package_price","company_name","created_at"])},
{name:"Pagos",headers:["Vacante","Empresa","Estado","Monto","Referencia","Enviado","Revisado","Creado"],rows:rows(payments.rows,["vacancy_code","company_name","status","amount","reference","submitted_at","reviewed_at","created_at"])},
{name:"Entregas",headers:["Vacante","Empresa","Estado","Enviada","Creada","Perfiles"],rows:rows(deliveries.rows,["vacancy_code","company_name","status","sent_at","created_at","profiles"])}
];const file=buildXlsx(sheets);reply.header("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");reply.header("Content-Disposition",`attachment; filename="empleos-pa-admin-${new Date().toISOString().slice(0,10)}.xlsx"`);return reply.send(file);});
app.get("/v1/admin/audit",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const raw=req.query?.limit;if(raw!==undefined&&(!/^\d+$/.test(String(raw))||Number(raw)<1||Number(raw)>100))return reply.code(400).send({error:"INVALID_LIMIT"});const limit=raw===undefined?50:Number(raw);const q=await db.query("select a.audit_id,a.action,a.entity_type,a.entity_id,a.metadata,a.created_at,u.email admin_email from admin_audit_log a join users u on u.user_id=a.admin_user_id order by a.created_at desc limit $1",[limit]);return {items:q.rows};});
app.patch("/v1/admin/vacancies/:code/status",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const next=typeof req.body?.status==="string"?req.body.status.toUpperCase():"";const allowed=["APROBADA","CANCELADA"];if(!allowed.includes(next))return reply.code(400).send({error:"INVALID_STATUS"});const client=await db.connect();try{await client.query("begin");const current=await client.query("select vacancy_id,status from vacancies where vacancy_code=$1 for update",[req.params.code]);if(!current.rowCount){await client.query("rollback");return reply.code(404).send({error:"VACANCY_NOT_FOUND"});}const transitions:Record<string,string[]>={RECIBIDA:["APROBADA","CANCELADA"],PENDIENTE_PAGO:["CANCELADA"],PAGO_EN_REVISION:["CANCELADA"],APROBADA:["CANCELADA"],EN_BUSQUEDA:["CANCELADA"]};if(!(transitions[current.rows[0].status]??[]).includes(next)){await client.query("rollback");return reply.code(409).send({error:"STATUS_TRANSITION_NOT_ALLOWED",from:current.rows[0].status,to:next});}if(next==="CANCELADA"){await client.query("delete from vacancy_candidates where vacancy_id=$1",[current.rows[0].vacancy_id]);await client.query("delete from vacancy_deliveries where vacancy_id=$1 and status='LISTA'",[current.rows[0].vacancy_id]);await client.query("update vacancy_payments set status='RECHAZADO',notes=case when nullif(trim(coalesce(notes,'')),'') is null then 'Solicitud cancelada por administración.' else notes||E'\\nSolicitud cancelada por administración.' end,reviewed_at=coalesce(reviewed_at,now()),updated_at=now() where vacancy_id=$1 and status in ('PENDIENTE','EN_REVISION')",[current.rows[0].vacancy_id]);}const q=await client.query("update vacancies set status=$1,updated_at=now() where vacancy_id=$2 returning vacancy_code,status,updated_at",[next,current.rows[0].vacancy_id]);await writeAdminAudit({adminUserId:req.authUser!.user_id,action:next==="CANCELADA"?"VACANCY_CANCELLED":"VACANCY_APPROVED",entityType:"VACANCY",entityId:String(req.params.code),metadata:{from:current.rows[0].status,to:next}},client);await client.query("commit");return {vacancy:q.rows[0]};}catch(e){await client.query("rollback").catch(()=>{});throw e;}finally{client.release();}});
}