import type {FastifyInstance} from "fastify";
import crypto from "node:crypto";
import {db} from "./db.js";
import {createSession,enableProfile,hashPassword,normalizeEmail,revokeSession,sessionUser,verifyPassword,issueReset,consumeReset} from "./auth.js";
import {destinationFor,publicProfile} from "./profiles.js";
import {sendEmail} from "./email.js";
import {config} from "./config.js";
const COOKIE="empleos_session";
const isProduction=process.env.NODE_ENV==="production";
const cookie={httpOnly:true,sameSite:(isProduction?"none":"lax") as "none"|"lax",secure:isProduction,path:"/"};
export async function authRoutes(app:FastifyInstance){
app.post("/v1/auth/register",async(req:any,reply)=>{const {email,password,role}=req.body??{};if(typeof email!=="string"||typeof password!=="string"||password.length<10||password.length>200||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password)||!["CANDIDATO","EMPRESA"].includes(role))return reply.code(400).send({error:"INVALID_REGISTRATION"});const normalized=normalizeEmail(email);if(!normalized||normalized.length>320||email.trim().length>320||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized))return reply.code(400).send({error:"INVALID_REGISTRATION"});const client=await db.connect();try{const hash=await hashPassword(password);await client.query("begin");const q=await client.query("insert into users(email,normalized_email,password_hash,role) values($1,$2,$3,$4) returning user_id,email,role",[email.trim(),normalized,hash,role]);await client.query("insert into user_profiles(user_id,profile_type) values($1,$2)",[q.rows[0].user_id,role]);const raw=crypto.randomBytes(32).toString("base64url");const tokenHash=crypto.createHash("sha256").update(raw).digest("hex");await client.query("insert into auth_sessions(user_id,token_hash,expires_at) values($1,$2,now()+interval '14 days')",[q.rows[0].user_id,tokenHash]);await client.query("commit");reply.setCookie(COOKIE,raw,{...cookie,maxAge:60*60*24*14});return {user:{...q.rows[0],profiles:[role],is_admin:false}};}catch(e:any){await client.query("rollback").catch(()=>{});if(e?.code==="23505")return reply.code(409).send({error:"ACCOUNT_EXISTS"});throw e;}finally{client.release();}});
app.post("/v1/auth/login",async(req:any,reply)=>{const {email,password}=req.body??{},requested=publicProfile(req.body?.profile);if(typeof email!=="string"||typeof password!=="string"||email.length>320||password.length>200||!email.trim())return reply.code(400).send({error:"INVALID_LOGIN"});const q=await db.query("select user_id,email,role,status,password_hash from users where normalized_email=$1",[normalizeEmail(email)]);const u=q.rows[0];const validPassword=u?.password_hash?await verifyPassword(u.password_hash,password):false;if(!u||u.status!=="ACTIVE"||!validPassword)return reply.code(401).send({error:"INVALID_CREDENTIALS"});if(requested&&u.role!=="ADMIN")await enableProfile(u.user_id,requested);const raw=await createSession(u.user_id);if(!raw)return reply.code(401).send({error:"INVALID_CREDENTIALS"});reply.setCookie(COOKIE,raw,{...cookie,maxAge:60*60*24*14});const user=await sessionUser(raw);return {user,redirect_to:destinationFor(user,requested,req.body?.return_to)};});
app.post("/v1/auth/logout",async(req:any,reply)=>{await revokeSession(req.cookies?.[COOKIE]);reply.clearCookie(COOKIE,{...cookie});return {ok:true};});
app.get("/v1/auth/me",async(req:any,reply)=>{const u=await sessionUser(req.cookies?.[COOKIE]);return u?{user:u}:reply.code(401).send({error:"UNAUTHENTICATED"});});
app.post("/v1/auth/profiles/:profile/enable",async(req:any,reply)=>{const user=await sessionUser(req.cookies?.[COOKIE]);if(!user)return reply.code(401).send({error:"UNAUTHENTICATED"});const profile=publicProfile(req.params?.profile);if(!profile)return reply.code(400).send({error:"INVALID_PROFILE"});if(user.role==="ADMIN")return reply.code(403).send({error:"ADMIN_PROFILE_CHANGE_FORBIDDEN"});await enableProfile(user.user_id,profile);return {user:await sessionUser(req.cookies?.[COOKIE])};});
app.post("/v1/auth/password/forgot",async(req:any,reply)=>{if(req.body?.email!==undefined&&typeof req.body.email!=="string")return reply.code(400).send({error:"INVALID_EMAIL"});const rawEmail=typeof req.body?.email==="string"?req.body.email:"";if(rawEmail.length>320)return reply.code(400).send({error:"INVALID_EMAIL"});const email=normalizeEmail(rawEmail);if(email&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return reply.code(400).send({error:"INVALID_EMAIL"});if(email){const q=await db.query("select user_id,email from users where normalized_email=$1 and status='ACTIVE'",[email]);if(q.rows[0]){const token=await issueReset(q.rows[0].user_id);if(!token)return {ok:true};const resetUrl=config.webUrl.replace(/\/$/,"")+"/restablecer?token="+encodeURIComponent(token);try{await sendEmail({to:q.rows[0].email,subject:"Restablece tu contraseña de Empleos.pa",text:"Recibimos una solicitud para restablecer tu contraseña de Empleos.pa.\n\nAbre este enlace para crear una nueva contraseña:\n"+resetUrl+"\n\nEl enlace vence en 30 minutos y solo puede usarse una vez. Si no solicitaste este cambio, puedes ignorar este mensaje."});}catch(error){app.log.error({err:error},"password reset email failed");}}}return {ok:true};});
app.post("/v1/auth/password/reset",async(req:any,reply)=>{const {token,password}=req.body??{};if(typeof token!=="string"||token.length<20||token.length>500||typeof password!=="string"||password.length<10||password.length>200||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password))return reply.code(400).send({error:"INVALID_RESET"});const ok=await consumeReset(token,await hashPassword(password));return ok?{ok:true}:reply.code(400).send({error:"RESET_EXPIRED_OR_USED"});});
}
