import type {FastifyInstance} from "fastify";import {db} from "./db.js";import {requireRoles} from "./rbac.js";
const fields=`candidate_id,candidate_code,status,full_name,phone,province,district,corregimiento,sector,work_profile,primary_job_area,other_job_areas,currently_working,available_from,availability_notes,work_locations,salary_expectation,education,has_experience,experience,skills,languages,computer_skills,driver_license,contact_preference,confirmations,valid_until,submitted_at,updated_at`;
function text(v:any){return typeof v==="string"?v.trim():null}function arr(v:any){return Array.isArray(v)?v:[]}
export async function candidateRoutes(app:FastifyInstance){
app.get("/v1/candidate/profile",{preHandler:requireRoles("CANDIDATO")},async(req,reply)=>{const q=await db.query(`select ${fields} from candidate_profiles where user_id=$1`,[req.authUser!.user_id]);return q.rows[0]?{profile:q.rows[0]}:reply.code(404).send({error:"PROFILE_NOT_FOUND"});});
app.put("/v1/candidate/profile",{preHandler:requireRoles("CANDIDATO")},async(req:any)=>{const b=req.body??{};const q=await db.query(`insert into candidate_profiles(user_id,full_name,phone,province,district,corregimiento,sector,work_profile,primary_job_area,other_job_areas,currently_working,available_from,availability_notes,work_locations,salary_expectation,education,has_experience,experience,skills,languages,computer_skills,driver_license,contact_preference,confirmations) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16::jsonb,$17,$18::jsonb,$19,$20,$21,$22,$23,$24::jsonb) on conflict(user_id) do update set full_name=excluded.full_name,phone=excluded.phone,province=excluded.province,district=excluded.district,corregimiento=excluded.corregimiento,sector=excluded.sector,work_profile=excluded.work_profile,primary_job_area=excluded.primary_job_area,other_job_areas=excluded.other_job_areas,currently_working=excluded.currently_working,available_from=excluded.available_from,availability_notes=excluded.availability_notes,work_locations=excluded.work_locations,salary_expectation=excluded.salary_expectation,education=excluded.education,has_experience=excluded.has_experience,experience=excluded.experience,skills=excluded.skills,languages=excluded.languages,computer_skills=excluded.computer_skills,driver_license=excluded.driver_license,contact_preference=excluded.contact_preference,confirmations=excluded.confirmations,updated_at=now() returning ${fields}`,[req.authUser!.user_id,text(b.full_name),text(b.phone),text(b.province),text(b.district),text(b.corregimiento),text(b.sector),text(b.work_profile),text(b.primary_job_area),text(b.other_job_areas),typeof b.currently_working==="boolean"?b.currently_working:null,text(b.available_from),text(b.availability_notes),text(b.work_locations),text(b.salary_expectation),JSON.stringify(arr(b.education)),typeof b.has_experience==="boolean"?b.has_experience:null,JSON.stringify(arr(b.experience)),text(b.skills),text(b.languages),text(b.computer_skills),text(b.driver_license),text(b.contact_preference),JSON.stringify(b.confirmations??{})]);return {profile:q.rows[0]};});
app.post("/v1/candidate/profile/submit",{preHandler:requireRoles("CANDIDATO")},async(req,reply)=>{const client=await db.connect();try{await client.query("begin");const q=await client.query("select * from candidate_profiles where user_id=$1 for update",[req.authUser!.user_id]);const p=q.rows[0];if(!p)return reply.code(404).send({error:"PROFILE_NOT_FOUND"});const c=p.confirmations??{};const valid=!!p.full_name&&!!p.phone&&!!p.province&&!!p.district&&!!p.corregimiento&&!!p.work_profile&&!!p.primary_job_area&&!!p.available_from&&!!p.work_locations&&!!p.skills&&typeof p.has_experience==="boolean"&&Array.isArray(p.education)&&p.education.length>0&&c.correct===true&&c.data_processing===true&&c.no_hiring_guarantee===true;if(!valid){await client.query("rollback");return reply.code(400).send({error:"PROFILE_INCOMPLETE"});}const u=await client.query("update candidate_profiles set candidate_code=coalesce(candidate_code,'EMP-'||lpad(nextval('candidate_code_seq')::text,6,'0')),status='ACTIVO',valid_until=current_date+interval '90 days',submitted_at=coalesce(submitted_at,now()),updated_at=now() where user_id=$1 returning candidate_code,status,valid_until,submitted_at",[req.authUser!.user_id]);await client.query("commit");return {profile:u.rows[0]};}catch(e){await client.query("rollback").catch(()=>{});throw e;}finally{client.release();}});
app.post("/v1/candidate/profile/renew",{preHandler:requireRoles("CANDIDATO")},async(req,reply)=>{const q=await db.query("update candidate_profiles set status='ACTIVO',valid_until=current_date+interval '90 days',updated_at=now() where user_id=$1 and candidate_code is not null and status in ('ACTIVO','VENCIDO') returning candidate_code,status,valid_until",[req.authUser!.user_id]);return q.rowCount?{profile:q.rows[0]}:reply.code(409).send({error:"PROFILE_NOT_RENEWABLE"});});
}
