function required(name:string){const value=(process.env[name]??"").trim();if(!value)throw new Error(`Missing required environment variable: ${name}`);return value;}
function integer(name:string,fallback:number,min:number,max:number){const raw=(process.env[name]??"").trim();if(!raw)return fallback;const value=Number(raw);if(!Number.isInteger(value)||value<min||value>max)throw new Error(`Invalid ${name}`);return value;}
function httpUrl(name:string,value:string,requiredHttps=false){let url:URL;try{url=new URL(value);}catch{throw new Error(`Invalid ${name}`);}if(!["http:","https:"].includes(url.protocol)||requiredHttps&&url.protocol!=="https:")throw new Error(`Invalid ${name}`);return url.toString().replace(/\/$/,"");}
const nodeEnv=(process.env.NODE_ENV??"development").trim();
const production=nodeEnv==="production";
const webUrl=httpUrl("WEB_URL",(process.env.WEB_URL??"http://localhost:3000").trim(),production);
const emailWebhookUrl=(process.env.EMAIL_WEBHOOK_URL??"").trim();
const deepSeekBaseUrl=httpUrl("DEEPSEEK_BASE_URL",(process.env.DEEPSEEK_BASE_URL??"https://api.deepseek.com").trim(),production);
if(emailWebhookUrl){httpUrl("EMAIL_WEBHOOK_URL",emailWebhookUrl,production);if(!(process.env.EMAIL_WEBHOOK_SECRET??"").trim())throw new Error("EMAIL_WEBHOOK_SECRET is required when EMAIL_WEBHOOK_URL is configured");}
export const config={port:integer("PORT",3001,1,65535),host:(process.env.HOST??"0.0.0.0").trim(),databaseUrl:required("DATABASE_URL"),nodeEnv,webUrl,candidateValidityDays:integer("CANDIDATE_VALIDITY_DAYS",45,1,365),emailWebhookUrl,emailWebhookSecret:(process.env.EMAIL_WEBHOOK_SECRET??"").trim(),emailFrom:(process.env.EMAIL_FROM??"Empleos.pa").trim(),requestPaymentMode:(process.env.REQUEST_PAYMENT_MODE??"FREE").toUpperCase()==="MANUAL"?"MANUAL":"FREE",deepSeekApiKey:(process.env.DEEPSEEK_API_KEY??"").trim(),deepSeekBaseUrl,deepSeekModel:(process.env.DEEPSEEK_MODEL??"deepseek-chat").trim(),deepSeekTimeoutMs:integer("DEEPSEEK_TIMEOUT_MS",12000,3000,30000)};
