import type {FastifyInstance} from "fastify";import {db} from "./db.js";import {requireRoles} from "./rbac.js";import {sendEmail} from "./email.js";
export async function deliveryRoutes(app:FastifyInstance){
app.get("/v1/admin/vacancies/:code/delivery",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const v=await db.query("select vacancy_id,vacancy_code,status,position,package,package_candidate_limit,package_price from vacancies where vacancy_code=$1",[req.params.code]);if(!v.rowCount)return reply.code(404).send({error:"VACANCY_NOT_FOUND"});const people=await db.query(`select cp.candidate_code,cp.full_name,cp.phone,u.email,cp.primary_job_area,cp.work_profile,cp.skills,cp.province,cp.district,vc.responded_at from vacancy_candidates vc join candidate_profiles cp on cp.candidate_id=vc.candidate_id join users u on u.user_id=cp.user_id where vc.vacancy_id=$1  order by vc.responded_at`,[v.rows[0].vacancy_id]);let d=await db.query("select * from vacancy_deliveries where vacancy_id=$1 order by created_at desc limit 1",[v.rows[0].vacancy_id]);return {vacancy:v.rows[0],delivery:d.rows[0]??null,candidates:people.rows};});
app.post("/v1/admin/vacancies/:code/delivery/prepare",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const v=await db.query("select vacancy_id,status,package_candidate_limit from vacancies where vacancy_code=$1",[req.params.code]);if(!v.rowCount)return reply.code(404).send({error:"VACANCY_NOT_FOUND"});const count=await db.query("select count(*)::int total from vacancy_candidates where vacancy_id=$1 ",[v.rows[0].vacancy_id]);if(!count.rows[0].total)return reply.code(409).send({error:"NO_SELECTED_CANDIDATES"});const limit=v.rows[0].package_candidate_limit;if(limit!==null&&limit!==undefined&&count.rows[0].total>Number(limit))return reply.code(409).send({error:"PACKAGE_CANDIDATE_LIMIT",limit:Number(limit)});const q=await db.query("insert into vacancy_deliveries(vacancy_id,status,notes) values($1,'LISTA',$2) returning *",[v.rows[0].vacancy_id,req.body?.notes||null]);return {delivery:q.rows[0]};});
app.post("/v1/admin/vacancies/:code/delivery/send",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const c=await db.connect();try{await c.query("begin");const v=await c.query("select vacancy_id from vacancies where vacancy_code=$1 for update",[req.params.code]);if(!v.rowCount){await c.query("rollback");return reply.code(404).send({error:"VACANCY_NOT_FOUND"});}const d=await c.query("select delivery_id,status from vacancy_deliveries where vacancy_id=$1 order by created_at desc limit 1 for update",[v.rows[0].vacancy_id]);if(!d.rowCount||d.rows[0].status!=="LISTA"){await c.query("rollback");return reply.code(409).send({error:"DELIVERY_NOT_READY"});}await c.query(`insert into vacancy_delivery_candidates(delivery_id,candidate_id,candidate_code,full_name,phone,email,primary_job_area,work_profile,skills,province,district,education,experience) select $1,cp.candidate_id,cp.candidate_code,cp.full_name,cp.phone,u.email,cp.primary_job_area,cp.work_profile,cp.skills,cp.province,cp.district,cp.education,cp.experience from vacancy_candidates vc join candidate_profiles cp on cp.candidate_id=vc.candidate_id join users u on u.user_id=cp.user_id where vc.vacancy_id=$2  on conflict(delivery_id,candidate_id) do nothing`,[d.rows[0].delivery_id,v.rows[0].vacancy_id]);await c.query(`insert into candidate_notifications(candidate_id,vacancy_id,type,title,message)
select vc.candidate_id,v.vacancy_id,'PROFILE_DELIVERED','Tu perfil estuvo en una búsqueda',
'Tu perfil estuvo incluido en una búsqueda para '||v.position||' en '||v.work_location||'. Una empresa podría contactarte. Mantente pendiente de tus medios de contacto.'
from vacancy_candidates vc join vacancies v on v.vacancy_id=vc.vacancy_id
where vc.vacancy_id=$1
on conflict(candidate_id,vacancy_id,type) do nothing`,[v.rows[0].vacancy_id]);await c.query("update vacancy_deliveries set status='ENVIADA',sent_at=now(),sent_by=$1,updated_at=now() where delivery_id=$2",[req.authUser!.user_id,d.rows[0].delivery_id]);await c.query("update vacancies set status='ENTREGADA',updated_at=now() where vacancy_id=$1",[v.rows[0].vacancy_id]);await c.query("commit");const notices=await db.query(`select n.notification_id,u.email,n.title,n.message from candidate_notifications n join candidate_profiles cp on cp.candidate_id=n.candidate_id join users u on u.user_id=cp.user_id where n.vacancy_id=$1 and n.type='PROFILE_DELIVERED' and n.emailed_at is null`,[v.rows[0].vacancy_id]);let emailed=0;for(const n of notices.rows){try{const sent=await sendEmail({to:n.email,subject:n.title,text:n.message});if(sent.sent){await db.query("update candidate_notifications set emailed_at=now() where notification_id=$1",[n.notification_id]);emailed++;}}catch(error){app.log.error({error,notification_id:n.notification_id},"candidate email notification failed");}}return {ok:true,delivery_status:"ENVIADA",vacancy_status:"ENTREGADA",email_notifications_sent:emailed};}catch(e){await c.query("rollback").catch(()=>{});throw e;}finally{c.release();}});
app.get("/v1/company/vacancies/:code/delivery",{preHandler:requireRoles("EMPRESA")},async(req:any,reply)=>{const v=await db.query(`select v.vacancy_id,v.vacancy_code,v.status,v.position from vacancies v join companies c on c.company_id=v.company_id where v.vacancy_code=$1 and c.owner_user_id=$2`,[req.params.code,req.authUser!.user_id]);if(!v.rowCount)return reply.code(404).send({error:"VACANCY_NOT_FOUND"});const d=await db.query("select delivery_id,status,sent_at,notes from vacancy_deliveries where vacancy_id=$1 and status=\'ENVIADA\' order by sent_at desc limit 1",[v.rows[0].vacancy_id]);if(!d.rowCount)return reply.code(404).send({error:"DELIVERY_NOT_AVAILABLE"});const p=await db.query("select candidate_code,full_name,phone,email,primary_job_area,work_profile,skills,province,district,education,experience,snapshot_at from vacancy_delivery_candidates where delivery_id=$1 order by full_name",[d.rows[0].delivery_id]);return {vacancy:v.rows[0],delivery:d.rows[0],candidates:p.rows};});
app.post("/v1/admin/vacancies/:code/close",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const q=await db.query("update vacancies set status='CERRADA',updated_at=now() where vacancy_code=$1 and status='ENTREGADA' returning vacancy_code,status",[req.params.code]);return q.rowCount?{vacancy:q.rows[0]}:reply.code(409).send({error:"VACANCY_NOT_DELIVERED"});});
}
