import type {FastifyInstance} from "fastify";import {db} from "./db.js";import {requireRoles} from "./rbac.js";
export async function matchingRoutes(app:FastifyInstance){
app.get("/v1/admin/vacancies/:code/matches",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const v=await db.query("select * from vacancies where vacancy_code=$1",[req.params.code]);if(!v.rowCount)return reply.code(404).send({error:"VACANCY_NOT_FOUND"});if(!["APROBADA","EN_BUSQUEDA"].includes(v.rows[0].status))return reply.code(409).send({error:"VACANCY_NOT_READY_FOR_MATCHING"});const x=v.rows[0];const q=await db.query(`select candidate_id,candidate_code,full_name,province,district,primary_job_area,skills,valid_until,
(lower(primary_job_area)=lower($1)) role_match,
(lower(work_locations) like '%'||lower($2)||'%') location_match,
coalesce((select array_agg(trim(s)) from unnest(string_to_array(coalesce($3,''),',')) s where trim(s)<>'' and lower(coalesce(skills,'')) like '%'||lower(trim(s))||'%'),'{}'::text[]) skills_overlap,
(case when nullif(trim(coalesce($4,'')),'') is null then null else lower(coalesce(education::text,'')) like '%'||lower(trim($4))||'%' end) education_match,
(case when nullif(trim(coalesce($5,'')),'') is null then null else lower(coalesce(experience::text,'')) like '%'||lower(trim($5))||'%' end) experience_match,
(available_from is null or available_from<=current_date) availability_match,
available_from,availability_notes
from candidate_profiles where status='ACTIVO' and valid_until>=current_date order by updated_at desc limit 100`,[x.position,x.work_location,x.skills,x.minimum_education,x.experience_requirement]);return {vacancy:{code:x.vacancy_code,position:x.position},items:q.rows};});
app.post("/v1/admin/vacancies/:code/candidates",{preHandler:requireRoles("ADMIN")},async(req:any,reply)=>{const ids=Array.isArray(req.body?.candidate_ids)?req.body.candidate_ids:[];if(!ids.length)return reply.code(400).send({error:"CANDIDATES_REQUIRED"});const v=await db.query("select vacancy_id,package,package_candidate_limit from vacancies where vacancy_code=$1 and status in ('APROBADA','EN_BUSQUEDA')",[req.params.code]);if(!v.rowCount)return reply.code(409).send({error:"VACANCY_NOT_READY"});const limit=v.rows[0].package_candidate_limit;if(limit!==null&&limit!==undefined&&ids.length>Number(limit))return reply.code(400).send({error:"PACKAGE_CANDIDATE_LIMIT",limit:Number(limit)});for(const id of ids)await db.query("insert into vacancy_candidates(vacancy_id,candidate_id,interest_status,contact_authorized,responded_at) values($1,$2,'INTERESADO',true,now()) on conflict(vacancy_id,candidate_id) do update set interest_status='INTERESADO',contact_authorized=true,responded_at=coalesce(vacancy_candidates.responded_at,now())",[v.rows[0].vacancy_id,id]);await db.query("update vacancies set status='EN_BUSQUEDA',updated_at=now() where vacancy_id=$1",[v.rows[0].vacancy_id]);return {ok:true,count:ids.length};});
app.get("/v1/candidate/opportunities",{preHandler:requireRoles("CANDIDATO")},async req=>{const q=await db.query(`select vc.vacancy_candidate_id,v.vacancy_code,v.position,v.work_location,v.schedule,v.salary,vd.sent_at from vacancy_candidates vc join candidate_profiles cp on cp.candidate_id=vc.candidate_id join vacancies v on v.vacancy_id=vc.vacancy_id left join lateral (select sent_at from vacancy_deliveries where vacancy_id=v.vacancy_id and status='ENVIADA' order by sent_at desc limit 1) vd on true where cp.user_id=$1 and vd.sent_at is not null order by vd.sent_at desc`,[req.authUser!.user_id]);return {items:q.rows};});
app.post("/v1/candidate/opportunities/:id/respond",{preHandler:requireRoles("CANDIDATO")},async(req:any,reply)=>{const interested=req.body?.interested;if(typeof interested!=="boolean")return reply.code(400).send({error:"INTEREST_REQUIRED"});const q=await db.query(`update vacancy_candidates vc set interest_status=$1,contact_authorized=$2,responded_at=now() from candidate_profiles cp where vc.vacancy_candidate_id=$3 and vc.candidate_id=cp.candidate_id and cp.user_id=$4 and vc.interest_status='PENDIENTE' returning vc.vacancy_candidate_id,vc.interest_status,vc.contact_authorized`,[interested?"INTERESADO":"NO_INTERESADO",interested,req.params.id,req.authUser!.user_id]);return q.rowCount?{response:q.rows[0]}:reply.code(404).send({error:"OPPORTUNITY_NOT_FOUND"});});
app.get("/v1/admin/vacancies/:code/authorized",{preHandler:requireRoles("ADMIN")},async(req:any)=>{const q=await db.query(`select cp.candidate_code,cp.full_name,cp.phone,u.email,cp.primary_job_area,cp.skills,cp.province,cp.district from vacancy_candidates vc join vacancies v on v.vacancy_id=vc.vacancy_id join candidate_profiles cp on cp.candidate_id=vc.candidate_id join users u on u.user_id=cp.user_id where v.vacancy_code=$1 and vc.interest_status='INTERESADO' and vc.contact_authorized=true order by vc.responded_at`,[req.params.code]);return {items:q.rows};});
}
