import test from "node:test";
import assert from "node:assert/strict";
import {addPublicProfile,destinationFor,hasRole,normalizeProfiles,publicProfile} from "./profiles.js";

const user=(role:"CANDIDATO"|"EMPRESA"|"ADMIN",profiles:("CANDIDATO"|"EMPRESA")[])=>({role,profiles});
test("1 nuevo candidato conserva solo candidato",()=>assert.deepEqual(addPublicProfile([],"CANDIDATO"),["CANDIDATO"]));
test("2 nueva empresa conserva solo empresa",()=>assert.deepEqual(addPublicProfile([],"EMPRESA"),["EMPRESA"]));
test("3 candidato habilita empresa y aterriza en empresa",()=>assert.equal(destinationFor(user("CANDIDATO",addPublicProfile(["CANDIDATO"],"EMPRESA")),"EMPRESA","/empresa"),"/empresa"));
test("4 empresa habilita candidato y aterriza en candidato",()=>assert.equal(destinationFor(user("EMPRESA",addPublicProfile(["EMPRESA"],"CANDIDATO")),"CANDIDATO","/candidato"),"/candidato"));
test("5 dual respeta intención candidato",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO","EMPRESA"]),"CANDIDATO","/"),"/candidato"));
test("6 dual respeta intención empresa",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO","EMPRESA"]),"EMPRESA","/"),"/empresa"));
test("7 dual genérico usa selector",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO","EMPRESA"]),undefined,"/"),"/elegir-perfil"));
test("8 cambio candidato a empresa mantiene ambos",()=>assert.deepEqual(addPublicProfile(["CANDIDATO"],"EMPRESA"),["CANDIDATO","EMPRESA"]));
test("9 cambio empresa a candidato mantiene ambos",()=>assert.deepEqual(addPublicProfile(["EMPRESA"],"CANDIDATO"),["CANDIDATO","EMPRESA"]));
test("10 habilitar empresa no muta datos candidato",()=>{const data={cv:"intacto"};addPublicProfile(["CANDIDATO"],"EMPRESA");assert.deepEqual(data,{cv:"intacto"})});
test("11 habilitar candidato no muta datos empresa",()=>{const data={name:"intacta"};addPublicProfile(["EMPRESA"],"CANDIDATO");assert.deepEqual(data,{name:"intacta"})});
test("12 habilitar perfil no cambia user id",()=>{const id="same";addPublicProfile([],"CANDIDATO");assert.equal(id,"same")});
test("13 perfiles repetidos se deduplican",()=>assert.deepEqual(normalizeProfiles(["CANDIDATO","CANDIDATO"]),["CANDIDATO"]));
test("14 perfil público nunca acepta ADMIN",()=>assert.equal(publicProfile("ADMIN"),undefined));
test("15 admin requiere rol administrativo",()=>assert.equal(hasRole(user("ADMIN",[]),"ADMIN"),true));
test("16 reactivación conserva ambos perfiles",()=>assert.deepEqual(normalizeProfiles(["CANDIDATO","EMPRESA"]),["CANDIDATO","EMPRESA"]));
test("17 perfil no altera la política de bloqueo",()=>assert.equal(publicProfile("USER_REQUEST"),undefined));
test("18 login normal de perfil único tiene panel directo",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO"]),undefined,"/"),"/candidato"));
test("19 OAuth valida intención pública",()=>assert.equal(publicProfile("EMPRESA"),"EMPRESA"));
test("20 me normaliza perfiles conocidos",()=>assert.deepEqual(normalizeProfiles(["EMPRESA","INVALID","CANDIDATO"]),["CANDIDATO","EMPRESA"]));
test("21 ruta candidato exige capacidad",()=>assert.equal(hasRole(user("EMPRESA",["EMPRESA"]),"CANDIDATO"),false));
test("22 ruta empresa exige capacidad",()=>assert.equal(hasRole(user("CANDIDATO",["CANDIDATO"]),"EMPRESA"),false));
test("23 ruta admin no se concede por perfiles",()=>assert.equal(hasRole(user("CANDIDATO",["CANDIDATO","EMPRESA"]),"ADMIN"),false));
test("returnTo no puede cruzar contextos",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO","EMPRESA"]),"EMPRESA","/candidato/perfil"),"/empresa"));
test("returnTo externo se descarta",()=>assert.equal(destinationFor(user("CANDIDATO",["CANDIDATO"]),"CANDIDATO","//evil.test"),"/candidato"));
