import Fastify from "fastify";
import cors from "@fastify/cors";
import cookie from "@fastify/cookie";
import {authRoutes} from "./auth-routes.js";
import {adminRoutes} from "./admin-routes.js";
import {portalRoutes} from "./portal-routes.js";
import {googleOAuthRoutes} from "./google-oauth.js";
import {candidateRoutes} from "./candidate-routes.js";
import {candidateItemsRoutes} from "./candidate-items-routes.js";
import {companyRoutes} from "./company-routes.js";
import {paymentRoutes} from "./payment-routes.js";
import {matchingRoutes} from "./matching-routes.js";
import {deliveryRoutes} from "./delivery-routes.js";
import {config} from "./config.js";
import {databaseReady,db} from "./db.js";
const app=Fastify({logger:true,bodyLimit:1024*1024,requestTimeout:15000});
const requestBuckets=new Map<string,{count:number;resetAt:number}>();
const requestBucketCleanup=setInterval(()=>{const now=Date.now();for(const [key,bucket] of requestBuckets)if(bucket.resetAt<=now)requestBuckets.delete(key);},60000);requestBucketCleanup.unref();
app.addHook("onRequest",async(req,reply)=>{if(!req.url.startsWith("/v1/auth/"))return;const now=Date.now();const key=req.ip+"|"+req.url.split("?")[0];const prior=requestBuckets.get(key);const bucket=!prior||prior.resetAt<=now?{count:1,resetAt:now+60000}:{count:prior.count+1,resetAt:prior.resetAt};requestBuckets.set(key,bucket);if(bucket.count>20){reply.header("Retry-After",String(Math.max(1,Math.ceil((bucket.resetAt-now)/1000))));return reply.code(429).send({error:"RATE_LIMITED"});}});
app.addHook("onSend",async(_req,reply,payload)=>{reply.header("X-Content-Type-Options","nosniff");reply.header("X-Frame-Options","DENY");reply.header("Referrer-Policy","no-referrer");reply.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");reply.header("Content-Security-Policy","default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");reply.header("Cache-Control","no-store");if(config.nodeEnv==="production")reply.header("Strict-Transport-Security","max-age=31536000; includeSubDomains");return payload;});
await app.register(cors,{origin:config.webUrl,credentials:true});
await app.register(cookie);
await app.register(authRoutes);
await app.register(adminRoutes);
await app.register(portalRoutes);
await app.register(googleOAuthRoutes);
await app.register(candidateRoutes);
await app.register(candidateItemsRoutes);
await app.register(companyRoutes);
await app.register(paymentRoutes);
await app.register(matchingRoutes);
await app.register(deliveryRoutes);
async function refreshCandidateLifecycle(){lifecycleLastRunAt=new Date().toISOString();try{const client=await db.connect();try{await client.query("begin");const expiring=await client.query("select candidate_id from candidate_profiles where status='ACTIVO' and valid_until<current_date order by candidate_id");if(expiring.rowCount){const ids=expiring.rows.map((r:any)=>r.candidate_id);await client.query("select distinct v.vacancy_id from vacancies v join vacancy_candidates vc on vc.vacancy_id=v.vacancy_id where vc.candidate_id=any($1::uuid[]) and v.status in ('RECIBIDA','PENDIENTE_PAGO','PAGO_EN_REVISION','APROBADA','EN_BUSQUEDA') order by v.vacancy_id for update of v",[ids]);const locked=await client.query("select candidate_id from candidate_profiles where candidate_id=any($1::uuid[]) and status='ACTIVO' and valid_until<current_date order by candidate_id for update",[ids]);const expiredIds=locked.rows.map((r:any)=>r.candidate_id);if(expiredIds.length){await client.query("update candidate_profiles set status='VENCIDO',updated_at=now() where candidate_id=any($1::uuid[]) and status='ACTIVO' and valid_until<current_date",[expiredIds]);await client.query("delete from vacancy_candidates vc using vacancies v where vc.vacancy_id=v.vacancy_id and vc.candidate_id=any($1::uuid[]) and v.status in ('RECIBIDA','PENDIENTE_PAGO','PAGO_EN_REVISION','APROBADA','EN_BUSQUEDA')",[expiredIds]);}}await client.query(`insert into candidate_notifications(candidate_id,type,title,message) select candidate_id,'PROFILE_EXPIRING','Tu perfil está por vencer','Tu perfil de Empleos.pa vence en 7 días. Si sigues buscando empleo, entra a tu cuenta y toca “Sigo buscando empleo · Renovar”.' from candidate_profiles where status='ACTIVO' and valid_until between current_date and current_date+7 on conflict do nothing`);await client.query("delete from auth_sessions where expires_at<now()-interval '30 days' or revoked_at<now()-interval '30 days'");await client.query("delete from password_reset_tokens where expires_at<now()-interval '7 days' or used_at<now()-interval '7 days'");await client.query("commit");lifecycleLastSuccessAt=new Date().toISOString();}catch(e){await client.query("rollback").catch(()=>{});throw e;}finally{client.release();}}catch(error){lifecycleLastErrorAt=new Date().toISOString();app.log.error(error,"candidate lifecycle refresh failed");}}
await refreshCandidateLifecycle();
const lifecycleTimer=setInterval(refreshCandidateLifecycle,60*60*1000);
lifecycleTimer.unref();
app.post("/v1/system/candidate-lifecycle",async(req:any,reply)=>{const expected=process.env.LIFECYCLE_CRON_SECRET??"";const supplied=typeof req.headers.authorization==="string"?req.headers.authorization.replace(/^Bearer\s+/i,""):"";if(!expected||supplied!==expected)return reply.code(401).send({error:"UNAUTHORIZED"});await refreshCandidateLifecycle();return {ok:true,ran_at:new Date().toISOString()};});
const startedAt=Date.now();
let lifecycleLastRunAt:string|null=null,lifecycleLastSuccessAt:string|null=null,lifecycleLastErrorAt:string|null=null;
app.get("/health",async()=>({status:"ok",service:"empleos-pa-api",uptime_seconds:Math.floor((Date.now()-startedAt)/1000),timestamp:new Date().toISOString(),lifecycle:{last_run_at:lifecycleLastRunAt,last_success_at:lifecycleLastSuccessAt,last_error_at:lifecycleLastErrorAt}}));
app.get("/ready",async(_request,reply)=>{try{const database=await databaseReady();return {status:"ready",database};}catch{reply.code(503);return {status:"not-ready",database:false};}});
async function shutdown(){clearInterval(lifecycleTimer);clearInterval(requestBucketCleanup);await app.close();await db.end();process.exit(0);}
process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
await app.listen({port:config.port,host:config.host});
