import Fastify from "fastify";
import cors from "@fastify/cors";
import cookie from "@fastify/cookie";
import {authRoutes} from "./auth-routes.js";
import {adminRoutes} from "./admin-routes.js";
import {portalRoutes} from "./portal-routes.js";
import {googleOAuthRoutes} from "./google-oauth.js";
import {candidateRoutes} from "./candidate-routes.js";
import {candidateItemsRoutes} from "./candidate-items-routes.js";
import {companyRoutes} from "./company-routes.js";
import {paymentRoutes} from "./payment-routes.js";
import {matchingRoutes} from "./matching-routes.js";
import {deliveryRoutes} from "./delivery-routes.js";
import {config} from "./config.js";
import {databaseReady,db} from "./db.js";
const app=Fastify({logger:true,bodyLimit:1024*1024,requestTimeout:15000});
app.addHook("onSend",async(_req,reply,payload)=>{reply.header("X-Content-Type-Options","nosniff");reply.header("X-Frame-Options","DENY");reply.header("Referrer-Policy","no-referrer");reply.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");reply.header("Cache-Control","no-store");return payload;});
await app.register(cors,{origin:config.webUrl,credentials:true});
await app.register(cookie);
await app.register(authRoutes);
await app.register(adminRoutes);
await app.register(portalRoutes);
await app.register(googleOAuthRoutes);
await app.register(candidateRoutes);
await app.register(candidateItemsRoutes);
await app.register(companyRoutes);
await app.register(paymentRoutes);
await app.register(matchingRoutes);
await app.register(deliveryRoutes);
async function refreshCandidateLifecycle(){try{await db.query("update candidate_profiles set status='VENCIDO',updated_at=now() where status='ACTIVO' and valid_until<current_date");await db.query(`insert into candidate_notifications(candidate_id,type,title,message) select candidate_id,'PROFILE_EXPIRING','Tu perfil está por vencer','Tu perfil de Empleos.pa vence en 7 días. Si sigues buscando empleo, entra a tu cuenta y toca “Sigo buscando empleo · Renovar”.' from candidate_profiles where status='ACTIVO' and valid_until between current_date and current_date+7 on conflict do nothing`);}catch(error){app.log.error(error,"candidate lifecycle refresh failed");}}
await refreshCandidateLifecycle();
const lifecycleTimer=setInterval(refreshCandidateLifecycle,60*60*1000);
lifecycleTimer.unref();
app.post("/v1/system/candidate-lifecycle",async(req:any,reply)=>{const expected=process.env.LIFECYCLE_CRON_SECRET??"";const supplied=typeof req.headers.authorization==="string"?req.headers.authorization.replace(/^Bearer\s+/i,""):"";if(!expected||supplied!==expected)return reply.code(401).send({error:"UNAUTHORIZED"});await refreshCandidateLifecycle();return {ok:true,ran_at:new Date().toISOString()};});
app.get("/health",async()=>({status:"ok",service:"empleos-pa-api"}));
app.get("/ready",async(_request,reply)=>{try{const database=await databaseReady();return {status:"ready",database};}catch{reply.code(503);return {status:"not-ready",database:false};}});
async function shutdown(){clearInterval(lifecycleTimer);await app.close();await db.end();process.exit(0);}
process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
await app.listen({port:config.port,host:config.host});
