import assert from 'node:assert/strict';
import type {FastifyInstance} from 'fastify';
import {db} from './db.js';
import {createSession,enableProfile} from './auth.js';
import {serviceContactRoutes} from './service-contact-routes.js';
import {serviceProviderRoutes} from './service-provider-routes.js';
export async function serviceContactIntegration(app:FastifyInstance){
  await app.register(serviceContactRoutes);await app.register(serviceProviderRoutes);
  const q=(sql:string,p:any[]=[])=>db.query(sql,p);
  const one=async(sql:string,p:any[]=[]) => (await q(sql,p)).rows[0];
  const user=async(name:string,role:'CANDIDATO'|'EMPRESA')=>{const r=await one(`insert into users(email,normalized_email,password_hash,role) values($1,$1,'isolated',$2) returning user_id`,[name+'@example.test',role]);await enableProfile(r.user_id,role);return {id:r.user_id,token:await createSession(r.user_id)};};
  const company=await user('contact-company','EMPRESA'),other=await user('contact-other-company','EMPRESA'),provider=await user('contact-provider','CANDIDATO'),wrongProvider=await user('contact-wrong-provider','CANDIDATO');
  const companyId=(await one(`insert into companies(owner_user_id,name) values($1,'Contact company') returning company_id`,[company.id])).company_id;
  const vacancy=await one(`insert into vacancies(company_id,request_type,position,work_location,province,district,corregimiento,schedule,skills,main_functions,package,package_price,status) values($1,'EVENTUAL','Electricista','Santiago','Veraguas','Santiago','Santiago','Diurno','Electricidad','Reparar','EVENTUAL_399',0,'APROBADA') returning vacancy_id,vacancy_code`,[companyId]);
  await q(`insert into service_provider_profiles(user_id,full_name,service_trade,service_province,service_district,service_corregimiento,contact_email,mobile_whatsapp,identity_document_type,identity_document_number,fixed_location_address) values($1,'Private Provider','Electricista','Veraguas','Santiago','Santiago','private@example.test','60000000','CEDULA','secret-document','secret-address')`,[provider.id]);
  await q(`insert into service_provider_verifications(user_id,provider,provider_session_id,status,verified_at) values($1,'DIDIT','contact-fixture','APPROVED',now())`,[provider.id]);
  const call=async(who:any,method:any,path:string,payload?:any,status=200)=>{const r=await app.inject({method,url:path,headers:{cookie:`empleos_session=${who.token}`},...(payload===undefined?{}:{payload})});assert.equal(r.statusCode,status,`${method} ${path}: ${r.body}`);return r.json();};
  const base=`/v1/company/vacancies/${vacancy.vacancy_code}`;
  await call(company,'GET','/v1/service-provider/profile',undefined,403);
  await call(provider,'GET',`${base}/service-matches`,undefined,403);
  await call(other,'GET',`${base}/service-matches`,undefined,404);
  const matches=await call(company,'GET',`${base}/service-matches`);assert.equal(matches.items.length,1);assert.equal(matches.pricing.unit_price,1.89);
  for(const field of ['full_name','contact_email','mobile_whatsapp','identity_document_number','fixed_location_address'])assert.equal(matches.items[0][field],undefined);
  await call(other,'POST',`${base}/service-contact-requests`,{provider_id:provider.id},404);
  const r=(await call(company,'POST',`${base}/service-contact-requests`,{provider_id:provider.id,price:0.01})).request;assert.equal(r.status,'REQUESTED');assert.equal(Number(r.price),1.89);
  assert.equal((await call(company,'POST',`${base}/service-contact-requests`,{provider_id:provider.id})).request.contact_request_id,r.contact_request_id);
  assert.equal((await one(`select count(*)::int n from yappy_payment_orders`)).n,0);
  const contact=`/v1/company/service-contact-requests/${r.contact_request_id}/contact`;
  await call(company,'GET',contact,undefined,403);await call(other,'GET',contact,undefined,404);
  assert.equal((await call(wrongProvider,'GET','/v1/service-provider/contact-requests')).items.length,0);
  assert.equal((await call(provider,'GET','/v1/service-provider/contact-requests')).items[0].contact_request_id,r.contact_request_id);
  const respond=`/v1/service-provider/contact-requests/${r.contact_request_id}/respond`;
  await call(wrongProvider,'POST',respond,{action:'ACCEPT'},404);
  assert.equal((await call(provider,'POST',respond,{action:'ACCEPT'})).request.status,'ACCEPTED_AWAITING_PAYMENT');
  assert.equal((await call(provider,'POST',respond,{action:'ACCEPT'})).request.status,'ACCEPTED_AWAITING_PAYMENT');
  await call(provider,'POST',respond,{action:'REJECT'},409);
  await call(company,'GET',contact,undefined,403);assert.equal((await one(`select count(*)::int n from yappy_payment_orders`)).n,0);
  // Isolated fixture stands for a confirmed settlement; production has no manual unlock route.
  await q(`update service_contact_requests set status='PAID',paid_at=now() where contact_request_id=$1`,[r.contact_request_id]);
  const revealed=(await call(company,'GET',contact)).contact;assert.equal(revealed.contact_email,'private@example.test');assert.equal(revealed.mobile_whatsapp,'60000000');assert.equal(revealed.identity_document_number,undefined);
  await call(other,'GET',contact,undefined,404);
  const rejectedVacancy=await one(`insert into vacancies(company_id,request_type,position,work_location,province,district,corregimiento,schedule,skills,main_functions,status) values($1,'EVENTUAL','Electricista','Santiago','Veraguas','Santiago','Santiago','Diurno','Electricidad','Reparar','APROBADA') returning vacancy_code`,[companyId]);
  const rejected=(await call(company,'POST',`/v1/company/vacancies/${rejectedVacancy.vacancy_code}/service-contact-requests`,{provider_id:provider.id})).request;
  const rejectPath=`/v1/service-provider/contact-requests/${rejected.contact_request_id}/respond`;
  assert.equal((await call(provider,'POST',rejectPath,{action:'REJECT'})).request.status,'DECLINED');
  await call(provider,'POST',rejectPath,{action:'REJECT'});await call(provider,'POST',rejectPath,{action:'ACCEPT'},409);
  await call(company,'GET',`/v1/company/service-contact-requests/${rejected.contact_request_id}/contact`,undefined,403);
  assert.equal((await one(`select count(*)::int n from yappy_payment_orders`)).n,0);
  console.log('SERVICE_CONTACTS PASS isolation/provider/accept/reject/no-charge/privacy/idempotency/settlement');
  return {company,other,provider,vacancy,acceptedId:r.contact_request_id,rejectedId:rejected.contact_request_id,call};
}
