"use client";
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import {YappyOperation} from './YappyOperation';
const labels:Record<string,string>={REQUESTED:'Esperando respuesta del prestador',ACCEPTED_AWAITING_PAYMENT:'Aceptada · pendiente de pago ($1.89)',DECLINED:'Rechazada · sin cobro',PAID:'Pago confirmado · contacto disponible'};
export function ServiceContacts({code}:{code:string}){
  const [matches,setMatches]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[contacts,setContacts]=useState<Record<string,any>>({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  async function load(){const r=await api(`/v1/company/vacancies/${code}/service-contact-requests`);setRequests(r.items??[]);}
  useEffect(()=>{load().catch(()=>setMsg('No se pudieron cargar las solicitudes.'));},[code]);
  async function find(){setBusy(true);try{const r=await api(`/v1/company/vacancies/${code}/service-matches`);setMatches(r.items??[]);setMsg(r.items?.length?'':'Todavía no hay prestadores verificados compatibles.');}catch{setMsg('Esta solicitud no está disponible para búsqueda.');}finally{setBusy(false);}}
  async function request(provider:string){setBusy(true);try{await api(`/v1/company/vacancies/${code}/service-contact-requests`,{method:'POST',body:JSON.stringify({provider_id:provider})});await load();setMsg('Solicitud enviada. El prestador puede aceptar o rechazarla.');}catch{setMsg('No se pudo enviar la solicitud.');}finally{setBusy(false);}}
  async function contact(id:string){try{const r=await api(`/v1/company/service-contact-requests/${id}/contact`);setContacts(x=>({...x,[id]:r.contact}));}catch{setMsg('El contacto requiere un pago confirmado.');}}
  return <div className="infoBox"><style>{`.serviceCompare{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:12px;align-items:start}.serviceCompare>article{min-width:0;border:1px solid #dce3ea;border-radius:16px;padding:16px;background:#fff}@media(max-width:620px){.serviceCompare{grid-template-columns:1fr}}`}</style><h2>Conexiones de servicios</h2><p>Solicitar contacto no tiene costo. Solo una conexión aceptada pasa a pago: $1.89. Si no acepta o rechaza, no se cobra. Los datos privados permanecen ocultos hasta confirmar el pago.</p><div className="portalActions"><button className="portalAction" disabled={busy} onClick={find}>Buscar prestadores compatibles</button><button className="portalAction secondaryPortal" disabled={busy} onClick={()=>load().catch(()=>setMsg('No se pudo actualizar.'))}>Actualizar solicitudes</button></div><p role="status">{msg}</p><div className="serviceCompare">{matches.map((m,i)=><article key={m.provider_id}><h3>Prestador compatible {i+1} · {m.service_trade}</h3><p>{m.service_province} · {m.service_district} · {m.available_days} · {m.available_hours}</p><button className="portalAction" disabled={busy||requests.some(r=>r.provider_id===m.provider_id)} onClick={()=>request(m.provider_id)}>Solicitar contacto</button></article>)}</div><div className="serviceCompare">{requests.map(r=><article key={r.contact_request_id}><h3>{r.service_trade}</h3><p>{labels[r.status]}</p>{r.status==='ACCEPTED_AWAITING_PAYMENT'&&<YappyOperation endpoint={`/v1/company/service-contact-requests/${r.contact_request_id}/payments/yappy`} amount={Number(r.price)} onConfirmed={()=>load().catch(()=>setMsg('Actualiza la solicitud para ver el contacto.'))}/>}{r.status==='PAID'&&<button className="portalAction" onClick={()=>contact(r.contact_request_id)}>Ver contacto</button>}{contacts[r.contact_request_id]&&<p>{Object.values(contacts[r.contact_request_id]).filter(Boolean).join(' · ')}</p>}</article>)}</div></div>;
}
export function ServiceContactInbox(){
  const [items,setItems]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  async function load(){const r=await api('/v1/service-provider/contact-requests');setItems(r.items??[]);}
  useEffect(()=>{load().catch(()=>setMsg('No se pudieron cargar tus solicitudes.'));},[]);
  async function respond(id:string,action:string){setBusy(true);try{await api(`/v1/service-provider/contact-requests/${id}/respond`,{method:'POST',body:JSON.stringify({action})});await load();setMsg(action==='ACCEPT'?'Aceptaste la conexión. La empresa debe pagar antes de ver tu contacto.':'Solicitud rechazada. No se cobra.');}catch{setMsg('No se pudo guardar la respuesta. Actualiza las solicitudes.');}finally{setBusy(false);}}
  return <section><h2>Solicitudes de contacto</h2><p>Decide si deseas conectar con la empresa. Tu perfil laboral es independiente de estas solicitudes.</p><button className="portalAction secondaryPortal" disabled={busy} onClick={()=>load().catch(()=>setMsg('No se pudo actualizar.'))}>Actualizar solicitudes</button><p role="status">{msg}</p>{!items.length&&<p>No tienes solicitudes de contacto.</p>}{items.map(r=><article className="infoBox" key={r.contact_request_id}><h3>{r.company_name} · {r.position}</h3><p>{r.province} · {r.district} · {r.schedule}</p><p>{labels[r.status]}</p>{r.status==='REQUESTED'&&<div className="portalActions"><button className="portalAction" disabled={busy} onClick={()=>respond(r.contact_request_id,'ACCEPT')}>Aceptar conexión</button><button className="portalAction secondaryPortal" disabled={busy} onClick={()=>respond(r.contact_request_id,'REJECT')}>Rechazar</button></div>}</article>)}</section>;
}
